<?php

namespace UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
//use Doctrine\ORM\QueryBuilder;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function isUser($username, $email)
	{
		$em = $this->getEntityManager();
		$qb = $em->createQueryBuilder();
		return $qb->select('u')
			->from('UserBundle:User', 'u')
			->where($qb->expr()->orX
				($qb->expr()->eq('u.userName', ':username'), 
				$qb->expr()->eq('u.email', ':email')))
			->setParameters(array(
			'username' => $username,
			'email' => $email
				))->getQuery()->setMaxResults( 1 );


	}
}
