# admin:
#     resource: "@AdminBundle/Resources/config/routing.php"
#     prefix:     "admin"
user: 
    # type: rest
    resource: "@UserBundle/Resources/config/routing.php"

fos_user:
    # type: rest
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"